import random

# ---------------------------------------------------------
# The Office Quotes Collection
# ---------------------------------------------------------
THE_OFFICE_QUOTES = [
    "“Sometimes I’ll start a sentence and I don’t even know where it’s going. I just hope I find it along the way.” — Michael Scott",
    "“I never thought I’d say this, but I think I ate too much bone marrow.” — Dwight Schrute",
    "“Everything I have I owe to this job… this stupid, wonderful, boring, amazing job.” — Jim Halpert",
    "“And I feel God in this Chili’s tonight.” — Pam Beesley",
    "“I normally don’t enjoy making people laugh.” — Angela Martin",
    "“I talk a lot, so I’ve learned to tune myself out.” — Kelly Kapoor",
    "“The Dunder Mifflin stock symbol is D.M.I. Do you know what that stands for? Dummies, Morons, and Idiots. Because that’s what you’d have to be to own it. And as one of those idiots, I believe the board owes me answers.” — Oscar Martinez",
    "“Me think, why waste time say lot word, when few word do trick.” — Kevin Malone",
    "“I’m glad Michael’s getting help. He has a lot of issues, and he’s stupid.” — Phyllis Lapin-Vance",
    "“It’s true. Around this office, in the past, I have been a little abrupt with people. But the doctor said, if I can’t find a new way to relate more positively to my surroundings, I’m going to die.” — Stanley Hudson",
    "“I wanna do a cartwheel. But real casual-like. Not enough to make a big deal out of it, but I know everyone saw it. One stunning, gorgeous cartwheel.” — Creed Bratton",
    "“A few years ago, my family was on a safari in Africa and my cousin, Mufasa, was um, he was trampled to death by a pack of wildebeests and um, we all took it really hard.” — Ryan Howard",
    "“No, I’m not going to tell them about the downsizing. If a patient has cancer, you don’t tell them.” — Michael Scott",
    "“Dwight mercy-killed Angela’s cat.” — Pam Beesley",
    "“I’m not superstitious, but I am a little stitious.” — Michael Scott",
    "“Look, it doesn’t take a genius to know that every organization thrives when it has two leaders. Go ahead, name a country that doesn’t have two presidents; a boat that sets sail without two captains. Where would Catholicism be without the popes?” — Oscar Martinez",
    "“An office is for not dying. An office is a place to live life to the fullest, to the max, to… an office is a place where dreams come true.” — Michael Scott",
    "“I run a small fake ID company from my car with a laminating machine that I swiped from the Sheriff’s station.” — Creed Bratton",
    "“I got six numbers. One more and it would have been a complete phone number.” — Kevin Malone",
    "“Would I rather be feared or loved? Easy. Both. I want people to be afraid of how much they love me.” — Michael Scott",
    "“The man is wearing sandals. I don’t need to see Oscar’s toes at work. Gross! I mean, he looks like he just got off the boat.” — Angela Martin",
    "“So this is my life — until I win the lottery. Or Pam finally writes that series of young adult books.” — Jim Halpert",
    "“If I don’t have some cake soon, I might die.” — Stanley Hudson",
    "“Guess what, I have flaws. What are they? Oh, I don’t know. I sing in the shower. Sometimes I spend too much time volunteering. Occasionally I’ll hit somebody with my car. So sue me.” — Michael Scott",
    "“Well, this is what happened. Uh, Ryan’s big project was the website, which wasn’t doing so well. So Ryan, to give the impression of sales, recorded them twice. Once as offices and once in the website sales, which is what we refer to in the business as misleading the shareholders. Another good term is fraud. The real crime, I think, was the beard.” — Oscar Martinez",
    "“The worst thing about prison was the dementors.” — Michael Scott",
    "“Identity theft is not a joke, Jim! Millions of families suffer every year.” — Dwight Schrute",
    "“Oh, I don’t think it’s blackmail. Angela just does what I ask her to do, so I won’t tell everyone that she’s cheating on Andy with Dwight. I think for it to be blackmail, it would have to be a formal letter.” — Phyllis Lapin-Vance",
    "“You know what they say about a car wreck, where it’s so awful you can’t look away? The Dundies are like a car wreck that you want to look away from, but you have to stare at it because your boss is making you.” — Pam Beesley",
    "“Do I need to be liked? Absolutely not. I like to be liked. I enjoy being liked. I have to be liked, but it’s not like this compulsive need to be liked, like my need to be praised.” — Michael Scott",
    "“I am proud to announce that there is a new addition to the Martin family. She’s hypoallergenic. She doesn’t struggle when you try to dress her. She’s a third-generation show cat. Her father was in Meet the Parents. Needless to say, she was very, very expensive.” — Angela Martin",
    "“I don’t talk trash, I talk smack. They’re totally different. Trash talk is hypothetical, like: Your mom is so fat she can eat the internet. But smack talk is happening like right now. Like: You’re ugly and I know it for a fact ’cause I got the evidence right there.” — Kelly Kapoor",
    "“I don’t care what they say about me. I just want to eat. Which I realize is a lot to ask for…at a dinner party.” — Pam Beesley",
    "“Life is short. Drive fast and leave a sexy corpse. That’s one of my mottos.” — Stanley Hudson",
    "“I just want to lie on the beach and eat hot dogs. That’s all I’ve ever wanted.” — Kevin Malone",
    "“Power points are the peacocks of the business world; all show, no meat.” — Dwight Schrute",
    "“My roommate wants to meet everybody. Because I’m pretty sure he thinks I’m making Dwight up. He is very real.” — Jim Halpert",
    "“No, Rose, they are not breathing. And they have no arms or legs… Where are they? You know what? If we come across somebody with no arms or legs, do we bother resuscitating them? I mean, what quality of life do we have there?” — Michael Scott",
    "“I wonder what people like about me. Probably my jugs.” — Phyllis Lapin-Vance",
    "“Oh, you’re paying way too much for worms. Who’s your worm guy?” — Creed Bratton",
    "“Look, I know the reason that you guys became accountants is because you’re not good at interacting with people. But guess what! From now on you guys are no longer losers! So give yourselves a round of applause.” — Kelly Kapoor",
    "“Fool me once, strike one. Fool me twice, strike three.” — Michael Scott",
    "“Sometimes the clothes at Gap Kids are too flashy, so I’m forced to go to the American Girl store and order clothes for large colonial dolls.” — Angela Martin",
    "“Today, smoking is going to save lives.” — Dwight Schrute",
    "“I don’t want to be married in a tent like a hobo.” — Angela Martin",
    "“It is not a good time for me to lose my job since I have some pretty big long-term plans in my personal life with Pam that I’d like her parents to be psyched about. So, I am about to do something very bold in this job that I’ve never done before: try.” — Jim Halpert",
    "“I have been trying to get on jury duty every year since I was 18 years old. To get to go sit it in an air-conditioned room, downtown, judging people, while my lunch is paid for… that is the life.” — Stanley Hudson",
    "“The only problem is whenever I try to make a taco, I get too excited and crush it.” — Kevin Malon",
    "“How is it possible that in five years, I’ve had two engagements and only one chair?” — Pam Beesley",
    "“Yeah, I’m not a temp anymore. I got Jim’s old job. Which means at my 10-year high school reunion, it will not say ‘Ryan Howard is a temp.’ It will say, ‘Ryan Howard is a junior sales associate at a mid-range paper supply firm.’ That’ll show ’em.” — Ryan Howard",
    "“I guess I’ve been working so hard, I forgot what it’s like to be hardly working.” — Michael Scott",
    "“Who says exactly what they’re thinking? What kind of a game is that?” — Kelly Kapoor",
    "“I’ve been involved in a number of cults, both a leader and a follower. You have more fun as a follower, but you make more money as a leader.” — Creed Bratton",
    "“Yes, I have a dream, and it’s not some MLK dream for equality. I want to own a decommissioned lighthouse. And I want to live at the top. And nobody knows I live there. And there’s a button that I can press and launch that lighthouse into space.” — Stanley Hudson",
    "“I’m guessing Angela is the one in the neighborhood that gives the trick-or-treaters toothbrushes, pennies, walnuts.” — Pam Beesley",
    "“I am running away from my responsibilities. And it feels good.” — Michael Scott",
    "“I once reported Oscar to the INS. Turns out he’s clean, but I’m glad I did it.” — Angela Martin",
    "“Besides having sex with men, I would say the Finer Things Club is the gayest thing about me.” — Oscar Martinez",
    "“If I were buying my coffin, I would get one with thicker walls so you couldn’t hear the other dead people.” — Dwight Schrute",
    "“We have a gym at home. It’s called the bedroom.” — Phyllis Lapin-Vance",
    "“If I had to, I could clean out my desk in five seconds, and nobody would ever know that I’d ever been here. And I’d forget, too.” — Ryan Howard",
    "“I don’t hate it. I just don’t like it at all and it’s terrible.” — Michael Scott",
    "“You guys I’m, like, really smart now. You don’t even know. You could ask me, ‘Kelly, what’s the biggest company in the world?’ And I’d be like, ‘blah blah blah, blah blah blah blah blah blah.’ Giving you the exact right answer.” — Kelly Kapoor",
    "“I am a black belt in gift wrapping.” — Jim Halpert",
    "“The people here are amazing debaters. I guess you can say they are master-baters.” — Kevin Malone",
    "“Who is Justice Beaver?” — Dwight Schrute",
    "“I want you to rub butter on my foot… Pam, please? I have Country Crock.” — Michael Scott",
    "“News flash: You are not special.” — Stanley Hudson",
    "“When you’re a kid, you assume your parents are soulmates. My kids are going to be right about that.” — Pam Beesley",
    "“And I knew exactly what to do. But in a much more real sense, I had no idea what to do.” — Michael Scott",
    "“I miss the days when there was only one party I didn’t want to go to.” — Ryan Howard",
    "“Sometimes I get so bored I just want to scream, and then sometimes I actually do scream. I just sort of feel out what the situation calls for.” — Kelly Kapoor",
    "“I am Beyonce, always.” — Michael Scott",
    "“I find the mystery genre disgusting. I hate being titillated.” — Angela Martin",
    "“If I can’t scuba, then what’s this all been about? What am I working toward?” — Creed Bratton",
    "“I say dance, they say, ‘How high?'” — Michael Scott",
    "“I wanted to eat a pig in a blanket, in a blanket.” — Kevin Malone",
    "“As a person who buys a lot of erotic cakes, it’s nice to be represented on one.” — Phyllis Lapin-Vance",
    "“Jim told me you could buy gaydar online.” — Dwight Schrute",
    "“I do not like pregnant women in my workspace. They’re always complaining. I have varicose veins, too. I have swollen ankles. I’m constantly hungry. Do you think my nipples don’t get sore too? Do you think I don’t need to know the fastest way to the hospital?” — Standley Hudson",
    "“I hate the idea that someone out there hates me. I even hate thinking that Al Qaeda hates me. I think if they got to know me, they wouldn’t hate me.” — Pam Beesley",
    "“Tell him to call me ASAP as possible.” — Michael Scott",
    "“Stanley just drank OJ out of my mug and didn’t seem to realize that it wasn’t his hot coffee. So, the question has to be asked, is there no limit to what he won’t notice?” — Jim Halpert",
    "“Ultimatums are key. Basically, nobody does anything for me anymore unless I threaten to kill myself.” — Kelly Kapoor",
    "“I love inside jokes. I’d love to be a part of one someday.” — Michael Scott",
    "“I want to be wine and dined and sixty-nined.” — Kevin Malone",
    "“Last year, Creed asked me how to set up a blog. Wanting to protect the world from being exposed to Creed’s brain, I opened up a Word document on his computer and put an address at the top. I’ve read some of it. Even for the internet, it’s… pretty shocking.” — Ryan Howard",
    "“Dwight you ignorant sl*t.” — Michael Scott",
    "“I already won the lottery. I was born in the US of A, baby. And as backup, I have a Swiss passport.” — Creed Bratton",
    "“Your body is a temple. You have to respect it. You can’t just whore it out.” — Angela Martin",
    "“I have decided that I’m going to be more honest. I’m gonna start telling people what I want, directly. So, look out world, ‘cuz ‘ol Pammy is gettin’ what she wants. And, don’t call me Pammy.” — Pam Beesley",
    "“It’s like I used to tell my wife. I do not apologize unless I think I’m wrong, and if you don’t like it, you can leave. And I say the same thing to my current wife, and I’ll say it to my next one, too.” — Stanley Hudson",
    "“I would say I kind of have an unfair advantage, because I watch reality dating shows like a hawk, and I learn. I absorb information from the strategies of the winners and the losers. Actually, I probably learn more from the losers.” — Michael Scott",
    "“I mean, I’m not a slut, but who knows.” — Kelly Kapoor",
    "“Michael is leaving. And apparently, they’ve already hired a new manager. And we’re meeting him today. It’s a lot to process — paperwork-wise.” — Oscar Martinez",
    "“Close your mouth, sweetie. You look like a trout.” — Phyllis Lapin-Vance",
    "“I wake up every morning in a bed that’s too small, drive my daughter to a school that’s too expensive, and then I go to work to a job for which I get paid too little. But on pretzel day? Well, I like pretzel day.” — Stanley Hudson",
    "“Nobody steals from Creed Bratton and gets away with it. The last person to do this disappeared. His name? Creed Bratton.” — Creed Bratton",
    "“Any man who says he totally understands women is a fool. Because they are un-understandable.” — Michael Scott",
    "“There’s a lot of beauty in ordinary things. Isn’t that kind of the point?” — Pam Beesly",
    "“I’ve got a golden ticket idea. Why don’t you skip on up to the roof and jump off?” — Stanley Hudson",
    "“I’m fast. To give you a reference point. I’m somewhere between a snake and a mongoose. And a panther.” — Dwight Schrute",
    "“There are always a million reasons not to do something.” — Jan Levinson",
    "“It’s a real shame because studies have shown that more information gets passed through water cooler gossip than through official memos. Which puts me at a disadvantage because I bring my own water to work.” — Dwight Schrute",
    "“Who’s the one who didn’t bring lice into the office? Meredith. Sure, I gave everybody pink eye once, and my ex keyed a few of their cars, and yeah, I BMed in the shredder on New Years. But I didn’t bring the lice in. That was all Pam.” — Meredith",
    "“You’re the people’s princess! Diana was nothing!” — Meredith",
    "“Tell ya one thing, I’m not gonna be a good mom tonight.” — Meredith",
    "“Hey everybody, he’s not in the men’s room. Although the seat was warm, so we may have just missed him.” — Meredith",
    "“Creed Bratton has never declared bankruptcy. When Creed Bratton gets in trouble, he transfers his debt to William Charles Scheider.” — Creed Bratton",
    "“Let’s put a smile on that face.” — Creed Bratton",
    "“When Pam gets Michael’s old chair, I get Pam’s old chair. Then I’ll have two chairs. Only one to go.” — Creed Bratton",
    "“You know a human can go on living for several hours after being decapitated.” — Creed Bratton",
    "“We didn’t play many video games in Scranton. Instead, we’d do stuff like… uh, Pam and I would sometimes hum the same high-pitched note and try to get Dwight to make an appointment with an ear doctor. And, uh, Pam called it… pretendinitis.” — Jim Halpert",
    "“So you’ve come to the master for guidance? Is this what you’re saying, grasshopper?” — Michael Scott",
    "“I think it’s great that the company’s making a commercial, because not very many people have heard of us. I mean, when I tell people I work at Dunder Mifflin, they think that we sell mufflers or muffins or mittens or… and frankly, all of those sound better than paper, so I let it slide.” — Jim Halpert",
    "“I’m always thinking one step ahead, like a carpenter that makes stairs.” — Andy Bernard",
    "“Rit-dit-dit-do-doo!” — Andy Bernard",
    "“I kinda know what it’s like to be in commercials. My nickname in high school used to be Kool-Aid Man.” — Kevin Malone",
    "“Boy, have you done lost your mind? Cause I’ll help you find it!” — Stanley Hudson",
    "“Today, smoking is going to save lives.” — Dwight Schrute",
    "“Ain’t no party like a Scranton party cause a Scranton party don’t stop!” — Michael Scott",
    "“I’m not offended by homosexuality. In the ’60s I made love to many, many women, often outdoors, in the mud and the rain… and it’s possible a man slipped in. (Shrugs) There’d be no way of knowing.” — Creed Bratton",
    "“In the parking lot today, there was a circus! The copier did tricks on the high-wire. A lady tried to give away a baby that looked like a cat. There was a Dwight impersonator and a Jim impersonator. A strongman crushed a turtle; I laughed, and I cried. Not bad for a day in the life of a dog food company.” — Creed Bratton",
    "“I can’t use Phyllis! Are you kidding me? The moment she steps off this bar, I’ll be launched into space! God, you’re so insensitive.” — Dwight Schrute",
    "“Bob Vance, Vance Refrigeration.” — Bob Vance",
    "“Mind if I steal my wife?” — Bob Vance",
    "“Should have burned this place down when I had the chance.” — Michael Scott",
    "“One day Michael came in and complained about a speed bump on the highway. I wonder who he ran over then.” — Jim Halpert"
]

# ---------------------------------------------------------
# Random Quote Generator
# ---------------------------------------------------------
def get_random_quote():
    """Return a random quote from The Office."""
    quote = random.choice(THE_OFFICE_QUOTES)
    return f"*{quote}*"
